### ISSUE TITLE
Jest encountered an unexpected token

### ISSUE THREAD

**Issue by jraleman** [JazzBrown1/react-context-menu-hooks#1]
Hello, I have encountered the following issue while running unit tests in my project.

It seems that the project is not configured correctly to work with Jest (it is failing because of the `import`/`export` syntax).

I am using version `27.5.1`, which seems to be more strict than version `>26`

<img width="1030" alt="err" src="https://user-images.githubusercontent.com/11222980/164539625-64e929d9-a37f-4ec1-90e4-1c2e8f99f355.png">

I got a workaround working in my project, declaring the following in `jest.config.js`

```js
module.exports = {
  // ...
  transformIgnorePatterns: ['node_modules/(?!(react-context-menu-hooks)/)'],
  // ...
};
```

**Comment by JazzBrown1** [comment]
Hi Jraleman thanks for reporting. I'll try to recreate this when I get some time at the weekend or next week.

Could you let me know what version of react are you using on your project?

thanks, jazz

**Comment by jraleman** [comment]
Hi JazzBrown1, sorry for getting to you a bit late.

My react version is `17.0.2`

**Comment by JazzBrown1** [comment]
Hi jraleman

I have fixed this and made a release please update to the latest version and let me know if you have any more issues.

thanks, Jazz

**Comment by jraleman** [comment]
Thanks @JazzBrown1, I don't longer see the issue. :)
